[package]
name = "singly_linked_list_array"
version = "0.1.0"
authors = ["Magnus <krummelur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
quickcheck = "1"
